1).Answer

In [19]:
import pandas as pd
import numpy as np
data = pd.Series(data = [1,2,3,4,5], index = list('abcde'))
print(data)
d_data= data.reindex(index =list('vijay'))
print(d_data)

a    1
b    2
c    3
d    4
e    5
dtype: int64
v    NaN
i    NaN
j    NaN
a    1.0
y    NaN
dtype: float64


2).Answer

In [24]:

data1 = pd.Series([1,5,3,4,6,7,8])
data2= pd.Series([6,7,3,3,2,4,5])
print("Addition\n",data1+data2)
print("Subtration\n",data1-data2)
print("Multiplication\n",data1*data2)
print("Division\n",data1/data2)


Addition
 0     7
1    12
2     6
3     7
4     8
5    11
6    13
dtype: int64
Subtration
 0   -5
1   -2
2    0
3    1
4    4
5    3
6    3
dtype: int64
Multiplication
 0     6
1    35
2     9
3    12
4    12
5    28
6    40
dtype: int64
Division
 0    0.166667
1    0.714286
2    1.000000
3    1.333333
4    3.000000
5    1.750000
6    1.600000
dtype: float64


3).Answer

In [25]:
data = pd.Series([1,2,3,4,5,6])
print(data)
print(type(data))
print(data.tolist())
print(type(data.tolist()))


0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.core.series.Series'>
[1, 2, 3, 4, 5, 6]
<class 'list'>


4).Answer

In [27]:
exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

data= pd.DataFrame(exam_data , index=labels)
print(data[data['score'].isnull()])


    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


5).Answer

In [29]:
from datetime import date
date = pd.to_datetime(str(date.today()), format='%Y-%m-%d')
print(date)

2019-12-07 00:00:00


6).Answer

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/vijaykumar10022/ML-IIIT/master/titanic.csv')
result = pd.pivot_table(df,'values=None', 'index=None', 'columns=None', "aggfunc='mean'", 'fill_value=None', 'margins=False', 'dropna=True', "margins_name='All'")
print(result)


7)Answer

In [34]:
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


8).Answer

In [40]:
data = np.array( [ (1,2,4,5),(2,1,5,4) ] )
print(data.flatten())
print(data.ravel())

[1 2 4 5 2 1 5 4]
[1 2 4 5 2 1 5 4]


9)>Answer

In [47]:
x =  np.arange(2, 11).reshape(3,3)
data=pd.DataFrame(x)
print(data.max)

<bound method DataFrame.max of    0  1   2
0  2  3   4
1  5  6   7
2  8  9  10>


10).Answer

In [48]:
data =np.arange(1, 10).reshape(3,3)
print(data)
print(np.hstack(data))
print(np.vstack(data))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
